### PR TITLE
Logo for XPanel

### PR DESCRIPTION
**Pull request by MrAnno**
I was told that the first iterations of the logo were too detailed/complex to be a good logo.
I'm going to consult with a graphic designer friend before finalizing this.

### CODE REVIEW

**Comment by norberttak** [comment]
Thanks @MrAnno for this beautiful logo :-)

**Comment by MsBicci** [comment]
Hi,

XPanel

We've simplified it a bit further. What do you think?

**Comment by norberttak** [comment]
Thanks @MsBicci! I like this logo very much ❤️ 
The first (with two gauges) seems to be slightly better for me.

**Comment by MrAnno** [comment]
This is the current version:
https://github.com/MrAnno/XPanel

Let us know if you want to change/remove/add anything :)

**Comment by norberttak** [comment]
It is perfect as is. Thanks a lot for this xmas present :-)

**Comment by MrAnno** [comment]
🎄

**Pull request merged**
